
//datasource
export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';
export const TOGGLE_SEARCHALL = 'TOGGLE_SEARCHALL'
export const TOGGLE_BLOCK_DATASOURCE = 'TOGGLE_BLOCK_DATASOURCE'
export const DELETE_DATASOURCE = 'DELETE_DATASOURCE'


//fetch test
export const FETCH_TEST_REQUEST = 'FETCH_TEST_REQUEST'
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS'
export const FETCH_TEST_FAILURE = 'FETCH_TEST_FAILURE'

//fetch sparql
export const FETCH_SPARQL_REQUEST = 'FETCH_SPARQL_REQUEST'
export const FETCH_SPARQL_SUCCESS = 'FETCH_SPARQL_SUCCESS'
export const FETCH_SPARQL_FAILURE = 'FETCH_SPARQL_FAILURE'

//fetch sparql
export const FETCH_SPARQL_ABOUTSUBJECT_REQUEST = 'FETCH_SPARQL_ABOUTSUBJECT_REQUEST'
export const FETCH_SPARQL_ABOUTSUBJECT_SUCCESS = 'FETCH_SPARQL_ABOUTSUBJECT_SUCCESS'
export const FETCH_SPARQL_ABOUTSUBJECT_FAILURE = 'FETCH_SPARQL_ABOUTSUBJECT_FAILURE'

