
//datasource
export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';

//fetch test
export const FETCH_TEST_REQUEST = 'FETCH_TEST_REQUEST'
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS'
export const FETCH_TEST_FAILURE = 'FETCH_TEST_FAILURE'

//fetch sparql
export const FETCH_SPARQL_REQUEST = 'FETCH_SPARQL_REQUEST'
export const FETCH_SPARQL_SUCCESS = 'FETCH_SPARQL_SUCCESS'
export const FETCH_SPARQL_FAILURE = 'FETCH_SPARQL_FAILURE'


export const SPARQL_GET_URI_FROM_LABEL_PENDING = 'SPARQL_GET_URI_FROM_LABEL_PENDING';
export const SPARQL_GET_URI_FROM_LABEL_FULFILLED = 'SPARQL_GET_URI_FROM_LABEL_FULFILLED';
export const SPARQL_GET_URI_FROM_LABEL_REJECTED = 'SPARQL_GET_URI_FROM_LABEL_REJECTED';
export const SPARQL_GET_TRIPLES_FROM_URI = 'SPARQL_GET_TRIPLES_FROM_URI';
export const SPARQL_GET_TRIPLES_FROM_URI_PENDING = 'SPARQL_GET_TRIPLES_FROM_URI_PENDING';
export const SPARQL_GET_TRIPLES_FROM_URI_FULFILLED = 'SPARQL_GET_TRIPLES_FROM_URI_FULFILLED';
export const SPARQL_GET_TRIPLES_FROM_URI_REJECTED = 'SPARQL_GET_TRIPLES_FROM_URI_REJECTED';

export const SPARQL_PENDING_REQUESTS_LIST = [
  SPARQL_GET_URI_FROM_LABEL_PENDING,
  SPARQL_GET_TRIPLES_FROM_URI_PENDING,
];

export const SPARQL_REJECTED_REQUESTS_LIST = [
  SPARQL_GET_URI_FROM_LABEL_REJECTED,
  SPARQL_GET_TRIPLES_FROM_URI_REJECTED,
];