
//datasource
export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';
export const TOGGLE_SEARCHALL = 'TOGGLE_SEARCHALL'
export const TOGGLE_BLOCK_DATASOURCE = 'TOGGLE_BLOCK_DATASOURCE'
export const DELETE_DATASOURCE = 'DELETE_DATASOURCE'
export const ADD_DATASOURCE = 'ADD_DATASOURCE'

//forcegraph settings
export const SET_FORCEGRAPH_SETTINGS = 'SET_FORCEGRAPH_SETTINGS'

//error
export const CREATE_ERROR = 'CREATE_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

//classes
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST'
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS'
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE'

export const SET_SELECTED_CLASS = 'SET_SELECTED_CLASS'

// instance from class
export const FETCH_INSTANCES_OF_CLASS_REQUEST = 'FETCH_INSTANCES_OF_CLASS_REQUEST'
export const FETCH_INSTANCES_OF_CLASS_SUCCESS = 'FETCH_INSTANCES_OF_CLASS_SUCCESS'
export const FETCH_INSTANCES_OF_CLASS_FAILURE = 'FETCH_INSTANCES_OF_CLASS_FAILURE'

export const SET_SELECTED_INSTANCE = 'SET_SELECTED_INSTANCE'

// nodes
export const SET_SELECTED_NODE = 'SET_SELECTED_NODE'
export const REMOVE_SELECTED_NODE = 'REMOVE_SELECTED_NODE'

export const SET_SELECTED_HISTORYGRAPH = 'SET_SELECTED_HISTORYGRAPH'


//fetch test
export const FETCH_TEST_REQUEST = 'FETCH_TEST_REQUEST'
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS'
export const FETCH_TEST_FAILURE = 'FETCH_TEST_FAILURE'

//fetch sparql
export const FETCH_SPARQL_REQUEST = 'FETCH_SPARQL_REQUEST'
export const FETCH_SPARQL_SUCCESS = 'FETCH_SPARQL_SUCCESS'
export const FETCH_SPARQL_FAILURE = 'FETCH_SPARQL_FAILURE'

//fetch sparql about subject
export const FETCH_SPARQL_ABOUTSUBJECT_REQUEST = 'FETCH_SPARQL_ABOUTSUBJECT_REQUEST'
export const FETCH_SPARQL_ABOUTSUBJECT_SUCCESS = 'FETCH_SPARQL_ABOUTSUBJECT_SUCCESS'
export const FETCH_SPARQL_ABOUTSUBJECT_FAILURE = 'FETCH_SPARQL_ABOUTSUBJECT_FAILURE'

//fetch about clicked nodes
export const FETCH_ABOUT_CLICKED_NODE_REQUEST = 'FETCH_ABOUT_CLICKED_NODE_REQUEST'
export const FETCH_ABOUT_CLICKED_NODE_SUCCESS = 'FETCH_ABOUT_CLICKED_NODE_SUCCESS'
export const FETCH_ABOUT_CLICKED_NODE_FAILURE = 'FETCH_ABOUT_CLICKED_NODE_FAILURE'

export const FETCH_PARENT_AND_SUB_NODES_REQUEST = 'FETCH_PARENT_AND_SUB_NODES_REQUEST'
export const FETCH_PARENT_AND_SUB_NODES_SUCCESS = 'FETCH_PARENT_AND_SUB_NODES_SUCCESS'
export const FETCH_PARENT_AND_SUB_NODES_FAILURE = 'FETCH_PARENT_AND_SUB_NODES_FAILURE'

//fetch history
export const FETCH_HISTORY_GRAPHS_REQUEST = 'FETCH_HISTORY_GRAPHS_REQUEST'
export const FETCH_HISTORY_GRAPHS_SUCCESS = 'FETCH_HISTORY_GRAPHS_SUCCESS' 
export const FETCH_HISTORY_GRAPHS_FAILURE = 'FETCH_HISTORY_GRAPHS_FAILURE' 

//
export const FETCH_FROM_HISTORIC_GRAPH_REQUEST = 'FETCH_FROM_HISTORIC_GRAPH_REQUEST'
export const FETCH_FROM_HISTORIC_GRAPH_SUCCESS = 'FETCH_FROM_HISTORIC_GRAPH_SUCCESS'
export const FETCH_FROM_HISTORIC_GRAPH_FAILURE = 'FETCH_FROM_HISTORIC_GRAPH_FAILURE'
