export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';
export const FETCH_SPARQL_REQUEST = 'FETCH_SPARQL_REQUEST';
export const FETCH_SPARQL_REQUEST_PENDING = 'FETCH_SPARQL_REQUEST_PENDING';
export const FETCH_SPARQL_REQUEST_FULFILLED = 'FETCH_SPARQL_REQUEST_FULFILLED';
export const FETCH_SPARQL_REQUEST_REJECTED = 'FETCH_SPARQL_REQUEST_REJECTED';
