export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';
export const SPARQL_GET_URI_FROM_LABEL = 'SPARQL_GET_URI_FROM_LABEL';
export const SPARQL_GET_URI_FROM_LABEL_PENDING = 'SPARQL_GET_URI_FROM_LABEL_PENDING';
export const SPARQL_GET_URI_FROM_LABEL_FULFILLED = 'SPARQL_GET_URI_FROM_LABEL_FULFILLED';
export const SPARQL_GET_URI_FROM_LABEL_REJECTED = 'SPARQL_GET_URI_FROM_LABEL_REJECTED';
export const SPARQL_GET_TRIPLES_FROM_URI = 'SPARQL_GET_TRIPLES_FROM_URI';
