export const SET_CURRENT_DATASOURCE = 'SET_CURRENT_DATASOURCE';
export const SPARQL_GET_URI_FROM_LABEL = 'SPARQL_GET_URI_FROM_LABEL';
export const SPARQL_GET_URI_FROM_LABEL_PENDING = 'SPARQL_GET_URI_FROM_LABEL_PENDING';
export const SPARQL_GET_URI_FROM_LABEL_FULFILLED = 'SPARQL_GET_URI_FROM_LABEL_FULFILLED';
export const SPARQL_GET_URI_FROM_LABEL_REJECTED = 'SPARQL_GET_URI_FROM_LABEL_REJECTED';
export const SPARQL_GET_TRIPLES_FROM_URI = 'SPARQL_GET_TRIPLES_FROM_URI';
export const SPARQL_GET_TRIPLES_FROM_URI_PENDING = 'SPARQL_GET_TRIPLES_FROM_PENDING';
export const SPARQL_GET_TRIPLES_FROM_URI_FULFILLED = 'SPARQL_GET_TRIPLES_FROM_FULFILLED';
export const SPARQL_GET_TRIPLES_FROM_URI_REJECTED = 'SPARQL_GET_TRIPLES_FROM_REJECTED';

export const SPARQL_PENDING_REQUESTS_LIST = [
  SPARQL_GET_URI_FROM_LABEL_PENDING,
  SPARQL_GET_TRIPLES_FROM_URI_PENDING,
];

export const SPARQL_REJECTED_REQUESTS_LIST = [
  SPARQL_GET_URI_FROM_LABEL_REJECTED,
  SPARQL_GET_TRIPLES_FROM_URI_REJECTED,
];
